#! /home/mskdl6/python-projects/finder/venv/bin/python

import os
import sys
import re
from colorama import init, Fore, Back

init(autoreset=True)
def finding(word, directory):
    
    flag = False
    
    for subdir, dirs, files in os.walk(directory):
        try:
            for file in files:
                filepath = subdir + os.sep + file
                printpath = re.sub(directory, '', filepath)
                pword ="\""+word+"\""
                if filepath.endswith(".php") or filepath.endswith(".js"):
                    with open(filepath, "r") as f:
                        lines = f.read().split("\n")
                        for i,line in enumerate(lines):
                            if word in line: 
                                flag = True
                                k = i+1
                                print(Fore.WHITE+Back.BLACK+pword+Fore.RESET+Back.RESET+" se encuentra en la linea "+Fore.WHITE+Back.BLACK+str(k)+Fore.RESET+Back.RESET+" de "+Fore.WHITE+Back.BLACK+str(printpath))
                    continue
                else:
                    continue
        except:
            continue
    if flag == False:
        print("Houston! We have a problem")
    
        

if __name__ == "__main__":
    i=1
    word = ""
    for i in range(len(sys.argv)):
        if i > 1:
            word = word + " " + sys.argv[i]
        elif i == 1:
            word = sys.argv[i]
        i=i+1
    
    directory = os.getcwd()
    
    finding(word, directory)

